default['supportworks']['install_dir'] = 'C:\Program Files (x86)'
default['supportworks']['root_password'] = ''
default['supportworks']['version'] = '8.2'
default['supportworks']['media'] = 'C:\SwMedia'
default['supportworks']['migrate_using_user'] = 'migrate'
default['supportworks']['migrate_using_password'] = 'password'
default['supportworks']['admin_password'] = 'password'
default['supportworks']['customizations'] = default['supportworks']['media'] + '\\' + 'customizations'